### ISSUE TITLE
Update `Getting Started` page with setup for Mac

### ISSUE THREAD

**Issue by RSijelmass** [Say-Their-Name/say-their-names-api#44]
I recently joined the _Say Their Names_ project and was eager to get started. PHP is new to me, so it is always a little daunting for new joiners to have a [`Getting Started`](https://github.com/Say-Their-Name/say-their-names-api/wiki/Getting-Started) setup page that isn't working on their local setup. I realised this has happened before, also with someone working on a Mac. 

There is a hyperlink in the `Getting Started` page named _"Other ways to setup are available here"_, but it is currently just looping back to the Wiki.

I want to implement a quick alternative local setup step-by-step for developers working on a MacBook.

**Comment by devingray** [comment]
Hi @RSijelmass if using mac, feel free to follow this guide so long, https://piperhaywood.com/laravel-valet-homebrew-mysql/

**Comment by devingray** [comment]
Updated
