### ISSUE TITLE
Inconsistent city data

### ISSUE THREAD

**Issue by dkhamsing** [Say-Their-Name/say-their-names-api#51]
**Describe the bug**
Seeing inconsistent `city` data from https://saytheirnames.dev/api/people 

```
{
	"id": 61,
	"full_name": "Rayshard Brooks",
	"identifier": "rayshard-brooks",
	"date_of_incident": "2020-06-12",
	"number_of_children": 4,
	"age": 27,
	"city": "Atlanta - GA",	
...
}, {
	"id": 25,
	"full_name": "Robert Fuller",
	"identifier": "robert-fuller",
	"date_of_incident": "2020-06-10",
	"number_of_children": null,
	"age": 24,
	"city": "Palmdale-CA",
```

**To Reproduce**
1. Go to https://saytheirnames.dev/api/people

**Expected behavior**
Should `Palmdale-CA` be `Palmdale - CA` or should the `- [state]` be removed?

**Comment by devingray** [comment]
Thank you for this, will pass on to DATA team
