### ISSUE TITLE
Data quality: derrick-scott

### ISSUE THREAD

**Issue by dkhamsing** [Say-Their-Name/say-their-names-api#52]
**Describe the bug**
For `"identifier": "derrick-scott"`, seeing unexpected extra `\n`'s at end of a the **their_story** value. 

**To Reproduce**
1. Go to https://saytheirnames.dev/api/people/derrick-scott
2. Observe `their_story` value, currently set to
```
"their_story": "Oklahoma City resident, Derrick Scott was an African-American man who died after a struggle in police custody in Oklahoma City, Oklahoma. He repeatedly told officers, “I can’t breathe,” and was recorded on body cameras. \"I don't care\", said officer Jarred Tipton.\n\nScott was pronounced dead at an Oklahoma City hospital about an hour after his arrest.\n\n\n\n", 
```

**Expected behavior**
We should not have the `\n`'s at the end.

Seeing similar issue for 
1. https://saytheirnames.dev/api/people/rashan-charles
2. https://saytheirnames.dev/api/people/joyce-clarke

**Comment by devingray** [comment]
Thank you, will check it

**Comment by devingray** [comment]
@dkhamsing This is normal, what team are you working in? is it a problem in your code? 

These are simple line breaks

**Comment by dkhamsing** [comment]
Not on any team .. seems this would cause layout issues if line breaks were rendered, we would see extra empty lines? Thanks for your time.

**Comment by dkhamsing** [comment]
Examples from iOS:

Normal
![841F6172-5ED0-44E8-BD62-530361E631A8](https://user-images.githubusercontent.com/4723115/85924417-08ea8f00-b847-11ea-830e-5ec5afc5e61d.png)

Extra empty lines 
![961857DC-079B-4EBE-B6C2-979FEF9B1B45](https://user-images.githubusercontent.com/4723115/85924419-0ab45280-b847-11ea-948d-fe09fa4de8a9.png)

**Comment by devingray** [comment]
Hi @dkhamsing Yes, I see what you mean, this is caused by extra line breaks in the Airtable Database. So we would need to remove it from there as the API simply pulls from that
