### ISSUE TITLE
Data Quality: url value contains a space

### ISSUE THREAD

**Issue by dkhamsing** [Say-Their-Name/say-their-names-api#53]
**Describe the bug**
In some news fields, seeing a space in the `url` value, is this expected?

**To Reproduce**
1. Go to https://saytheirnames.dev/api/people/jamel-floyd
2. Inspect the `news` entry and see that there is a space in front of the url value:

`"url": " https://www.cbsnews.com/news/federal-inmate-jamel-floyd-dies-pepper-sprayed-by-guards-new-york"
		},`

```
{
	"news": [{
			"url": "https://edition.cnn.com/2020/06/04/us/jamel-floyd-brooklyn-prison-death-pepper-spray/index.html"
		},
		{
			"url": " https://www.cbsnews.com/news/federal-inmate-jamel-floyd-dies-pepper-sprayed-by-guards-new-york"
		},
		{
			"url": " https://www.newsweek.com/jamel-floyd-death-stirs-fresh-protests-family-says-prisoner-was-murdered-mace-1508853"
		}
	]
}
```

**Expected behavior**
There should not be a space in front of https.

**Comment by devingray** [comment]
Merged
